#!/bin/sh
# \
exec tclsh $0 $@

source $env(LAUNCHER_HOME)/launcher_imp.tcl

# Clean up log files.
if {[catch {glob *.log} rc] == 0} {
    foreach filename $rc {
    	file delete $filename
    }
}

Launcher::Init
set taskfile [lindex $argv 0]
if {[catch {Launcher::Runit $taskfile} rc]} {
    puts "error = $rc"
    exit -1
}

set continue 1
while {$continue} {
    puts "Tasks running. Enter x to stop the tasks and exit."
    gets stdin ans 
    if {$ans == "x"} {
	Launcher::Stopit	
	set continue 0
    }
}

exit 0
